[window]
decorations = "full"
opacity = 1
dynamic_title = true

  [window.dimensions]
  columns = 140
  lines = 38

[font]
size = 14
  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

  [font.offset]
  x = 0
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0

[shell]
		program = "/bin/zsh"

[scrolling]
history = 10_000
multiplier = 3

[cursor]
style = "Underline"
unfocused_hollow = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#949494"
blue = "#74b2ff"
cyan = "#85dc85"
green = "#36c692"
magenta = "#ae81ff"
red = "#ff5189"
white = "#e4e4e4"
yellow = "#c6c684"

[colors.cursor]
cursor = "#8e8e8e"
text = "#080808"

[colors.normal]
black = "#323437"
blue = "#80a0ff"
cyan = "#79dac8"
green = "#8cc85f"
magenta = "#cf87e8"
red = "#ff5d5d"
white = "#c6c6c6"
yellow = "#e3c78a"

[colors.primary]
background = "#080808"
bright_foreground = "#eeeeee"
foreground = "#bdbdbd"

[colors.selection]
background = "#b2ceee"
text = "#080808"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Back"
mods = "Option"
chars = "\u001b"

[[keyboard.bindings]]
key = "Right"
mods = "Option"
chars = "\u001bF"
[[keyboard.bindings]]
key = "Left"
mods = "Option"
chars = "\u001bB"
