[terminal.shell]
program = "/opt/homebrew/bin/nu"

[window]
decorations = "full"
opacity = 1
dynamic_title = true

  [window.dimensions]
  columns = 140
  lines = 38

  [window.padding]
  x = 5
  y = 5

[font]
size = 12

	[font.normal]
	family = "JetBrainsMono Nerd Font"
	style = "Regular"

  # [font.offset]
  # x = 0
  # y = 0

  # [font.glyph_offset]
  # x = 0
  # y = 0

[scrolling]
history = 10_000
multiplier = 3

[cursor]
# style = "Underline"
unfocused_hollow = true

[colors.primary]
background = "#000000"
foreground = "#b6b6b6"

[colors.normal]
black = "#000000"
green = "#00a600"
yellow = "#999900"
magenta = "#b200b2"
cyan = "#00a6b2"
white = "#bfbfbf"

[colors.bright]
black = "#666666"
green = "#00d900"
yellow = "#e5e500"
magenta = "#e500e5"
cyan = "#00e5e5"
white = "#e5e5e5"

# [[keyboard.bindings]]
# key = "N"
# mods = "Command"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Back"
mods = "Alt"
chars = "\u0017"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bF"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bB"

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"
